
# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 0, size: 0.161},
    {id: 2, size: 0.161},
    {id: 1, size: 0.161},
    {id: 3, size: 0.161},
    {id: 4, size: 0.161},
    {id: 5, size: 0.161},
    {id: 6, size: 0.161},
    {id: 7, size: 0.161},
    {id: 8, size: 0.161},
    {id: 9, size: 0.161},
    {id: 10, size: 0.161},
    {id: 11, size: 0.161},
    {id: 12, size: 0.161},
    {id: 13, size: 0.161},
    {id: 14, size: 0.161},
    {id: 15, size: 0.161},
    {id: 16, size: 0.161},
    {id: 17, size: 0.161},
    {id: 18, size: 0.161},
    {id: 19, size: 0.161},
    {id: 20, size: 0.0755},
    {id: 21, size: 0.0755},
    {id: 22, size: 0.0755},
    {id: 23, size: 0.0755},
    {id: 24, size: 0.0755},
    {id: 25, size: 0.0755},
    {id: 26, size: 0.0755},
    {id: 27, size: 0.0755},
    {id: 28, size: 0.0755},
    {id: 29, size: 0.0755},
    {id: 30, size: 0.0755},
    {id: 31, size: 0.0755},
    {id: 32, size: 0.0755},
    {id: 33, size: 0.0755},
    {id: 34, size: 0.0755},
    {id: 35, size: 0.0755},
    # for testing bundles:
    {id: 48, size: 0.112},
    {id: 45, size: 0.078},
    {id: 46, size: 0.078},
    {id: 49, size: 0.078},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'test_bundle',
      layout:
        [
          {id: 48, size: 0.112, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 46, size: 0.078, x: -0.0867, y: -0.1191, z: -0.0029, qw: 1.0000, qx: 0.0020, qy: 0.0029, qz: 0.0065},
          {id: 45, size: 0.078, x: -0.1171, y: 0.0815, z: 0.0024, qw: 0.9999, qx: 0.0081, qy: 0.0077, qz: 0.0125},
          {id: 49, size: 0.078, x: 0.0203, y: -0.1202, z: -0.0042, qw: 0.7072, qx: 0.0018, qy: 0.0039, qz: 0.7070}
        ]
    }

    {
      name: 'my_bundle',
      layout:
        [
          {id: 2, size: 0.16, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 6, size: 0.16, x: -0.4012, y: -0.0030, z: -0.0073, qw: 0.9991, qx: 0.0435, qy: 0.0004, qz: 0.0004},
          {id: 7, size: 0.16, x: 0.4045, y: -0.0108, z: -0.0207, qw: 0.9993, qx: 0.0339, qy: 0.0113, qz: -0.0066},
          {id: 5, size: 0.16, x: -0.7555, y: 0.0033, z: -0.0144, qw: 0.9999, qx: 0.0100, qy: -0.0053, qz: -0.0022},
          {id: 20, size: 0.08, x: 0.0106, y: 0.6962, z: -0.0174, qw: 0.9999, qx: -0.0146, qy: -0.0041, qz: -0.0045},
          {id: 23, size: 0.08, x: -0.0001, y: -0.6967, z: 0.0019, qw: 0.9998, qx: -0.0118, qy: -0.0133, qz: -0.0068},
          {id: 22, size: 0.08, x: 0.0008, y: -0.2466, z: 0.0134, qw: 1.0000, qx: 0.0057, qy: 0.0068, qz: 0.0020},
          {id: 21, size: 0.08, x: 0.0051, y: 0.2514, z: 0.0015, qw: 0.9999, qx: 0.0058, qy: 0.0090, qz: -0.0096},
          {id: 24, size: 0.08, x: -0.5746, y: -0.0004, z: -0.0173, qw: 0.9949, qx: 0.0445, qy: 0.0905, qz: 0.0020},
          {id: 26, size: 0.08, x: 0.2003, y: -0.0018, z: -0.0089, qw: 0.9997, qx: -0.0119, qy: -0.0190, qz: 0.0000},
          {id: 25, size: 0.08, x: -0.2009, y: 0.0001, z: -0.0007, qw: 0.9997, qx: 0.0147, qy: 0.0182, qz: 0.0011},
          {id: 1, size: 0.16, x: 0.0101, y: 0.4973, z: -0.0175, qw: 0.9995, qx: -0.0290, qy: 0.0085, qz: -0.0037},
          {id: 27, size: 0.08, x: 0.5737, y: -0.0084, z: -0.0195, qw: 1.0000, qx: -0.0003, qy: 0.0068, qz: -0.0010},
          {id: 3, size: 0.16, x: -0.0009, y: -0.4990, z: -0.0030, qw: 0.9999, qx: 0.0126, qy: 0.0103, qz: 0.0023},
          {id: 8, size: 0.16, x: 0.7567, y: -0.0080, z: -0.0246, qw: 0.9999, qx: -0.0009, qy: 0.0116, qz: 0.0032},
          {id: 0, size: 0.16, x: 0.0202, y: 0.9242, z: -0.0252, qw: 0.9993, qx: -0.0323, qy: 0.0155, qz: -0.0083},
          {id: 4, size: 0.16, x: -0.0015, y: -0.9440, z: -0.0340, qw: 0.9996, qx: 0.0184, qy: -0.0208, qz: 0.0010}
        ]
    }
  ]
